/**
 * `CR-50` / [ADR-0089](../../../docs/decisions/0089-media-correctness-four-boundaries.md) §1 — the
 * end-to-end delivery proof, per provider.
 *
 * The engine answers a `read_media` call with a short TEXT descriptor and delivers the bytes on a
 * synthesized `user` message carrying a top-level, handle-only `media` part. This file takes that exact
 * message pair and pushes it through the real machinery — `FallbackChain.#materializeMedia` resolving the
 * handle, then each shipped adapter lowering the result — and asserts the media actually arrives on the
 * wire, for **all three** providers.
 *
 * It is the half that could not be proved in `@relavium/core`: the adapters are not exported from the seam
 * and `defaultProviders()` takes no transport, so the wire payload can only be captured here. The producing
 * half — that the turn loop emits precisely this pair, with the engine-authored preamble — is pinned in
 * `packages/core/src/engine/agent-turn.test.ts`. The two are written against the same literal shape on
 * purpose; if one is edited without the other, the shape they share is what to reconcile.
 *
 * What the assertions are chosen to catch: the pre-`CR-50` design put the bytes in `tool_result.media`,
 * where **nothing lowered them** — the chain's re-materialization never descends into a tool result and
 * OpenAI's `role:'tool'` lowering filters the message to `tool_result` parts. So every test below asserts
 * the media on the PROVIDER PAYLOAD, never merely that the request was well-formed.
 */

import { describe, expect, it } from 'vitest';

import { createAnthropicAdapter } from './adapters/anthropic.js';
import { createGeminiAdapter } from './adapters/gemini.js';
import { createOpenAiAdapter } from './adapters/openai.js';
import { FallbackChain } from './fallback-chain.js';
import type { LlmMessage, LlmProvider } from './types.js';

/** The lowered request body, as JSON. A non-string body is a harness error, not a silent `{}`. */
function parseJsonBody(init: RequestInit | undefined): unknown {
  if (typeof init?.body !== 'string') {
    throw new Error('expected a string JSON request body from the adapter');
  }
  return JSON.parse(init.body) as unknown;
}

const HANDLE = `media://sha256-${'a'.repeat(64)}`;
const PNG_BASE64 = 'aW1hZ2U=';
const TOOL_CALL_ID = 'call-1';

/**
 * The message pair the engine produces for a `read_media` call (`agent-turn.ts`). Written out literally
 * rather than imported, because `@relavium/llm` cannot depend on `@relavium/core` — the same literal is
 * asserted on the producing side.
 */
function readMediaExchange(): LlmMessage[] {
  return [
    { role: 'user', content: [{ type: 'text', text: 'look at the image' }] },
    {
      role: 'assistant',
      content: [
        { type: 'tool_call', id: TOOL_CALL_ID, name: 'read_media', args: { handle: HANDLE } },
      ],
    },
    {
      role: 'tool',
      content: [
        {
          type: 'tool_result',
          toolCallId: TOOL_CALL_ID,
          result: `image/png, 5 bytes, ${HANDLE} — attached below.`,
        },
      ],
    },
    {
      role: 'user',
      content: [
        {
          type: 'text',
          text: "[Relavium] 1 media attachment returned by the `read_media` tool, delivered below. This message was generated by Relavium to carry the tool's output; it is not from the user.",
        },
        { type: 'media', mimeType: 'image/png', source: { kind: 'handle', ref: HANDLE } },
      ],
    },
  ];
}

/** Run `messages` through the chain (so the handle is resolved exactly as production resolves it). */
async function sendThroughChain(
  provider: LlmProvider,
  model: string,
  messages: LlmMessage[] = readMediaExchange(),
): Promise<void> {
  const chain = new FallbackChain([{ provider, model, maxAttempts: 1 }], {
    keyFor: () => Promise.resolve('test-key'),
    sleep: () => Promise.resolve(),
    resolveForEgress: (handle) => {
      expect(handle).toBe(HANDLE); // the CANONICAL handle, re-resolved per attempt (ADR-0043 §1)
      return Promise.resolve({ kind: 'base64', data: PNG_BASE64 });
    },
  });
  await chain.generate({ model, messages, tools: [] });
}

/**
 * Deep-search a lowered provider payload for the base64 image, wherever that provider puts it.
 *
 * Deliberately position-agnostic, because the three providers put it in three different places. It is
 * therefore only half an assertion: it proves the image was LOWERED, not that it sits where it belongs.
 * The position is pinned on the producing side (`agent-turn.test.ts` asserts the tool results stay
 * contiguous and exactly one `user` message follows) and by `toolResultsContiguous` below, which is the
 * property a provider actually rejects.
 */
function containsImage(payload: unknown): boolean {
  if (typeof payload === 'string') return payload.includes(PNG_BASE64);
  if (Array.isArray(payload)) return payload.some(containsImage);
  if (typeof payload === 'object' && payload !== null) {
    return Object.values(payload).some(containsImage);
  }
  return false;
}

/**
 * The message pair for a response with TWO `read_media` calls — the shape a review found broke every
 * provider when the synthesized message was appended inside the dispatch loop.
 */
function parallelReadMediaExchange(): LlmMessage[] {
  return [
    { role: 'user', content: [{ type: 'text', text: 'look at both' }] },
    {
      role: 'assistant',
      content: [
        { type: 'tool_call', id: 'c1', name: 'read_media', args: { handle: HANDLE } },
        { type: 'tool_call', id: 'c2', name: 'read_media', args: { handle: HANDLE } },
      ],
    },
    {
      role: 'tool',
      content: [
        { type: 'tool_result', toolCallId: 'c1', result: 'image/png, 5 bytes — attached below.' },
      ],
    },
    {
      role: 'tool',
      content: [
        { type: 'tool_result', toolCallId: 'c2', result: 'image/png, 5 bytes — attached below.' },
      ],
    },
    {
      role: 'user',
      content: [
        {
          type: 'text',
          text: '[Relavium] 2 media attachments returned by the `read_media` tool calls, delivered below.',
        },
        { type: 'media', mimeType: 'image/png', source: { kind: 'handle', ref: HANDLE } },
        { type: 'media', mimeType: 'image/png', source: { kind: 'handle', ref: HANDLE } },
      ],
    },
  ];
}

/**
 * Every `tool` message answering an assistant `tool_calls` turn is contiguous — no other role between them.
 *
 * This is the property the providers actually enforce, and the one `containsImage` cannot see: OpenAI 400s
 * naming the unanswered `tool_call_id`, Gemini requires the `functionResponse` count to match the
 * `functionCall` count, and Anthropic merges adjacent user turns so an image ends up BETWEEN two
 * `tool_result` blocks. Asserted on the canonical list, because a broken list breaks all three.
 */
function toolResultsContiguous(messages: readonly LlmMessage[]): boolean {
  const roles = messages.map((m) => m.role);
  const first = roles.indexOf('tool');
  if (first === -1) return true;
  const last = roles.lastIndexOf('tool');
  return roles.slice(first, last + 1).every((role) => role === 'tool');
}

describe('read_media delivery reaches the model as media (`CR-50`, ADR-0089 §1)', () => {
  it('PARALLEL calls keep their tool results contiguous — the shape all three providers require', () => {
    expect(toolResultsContiguous(parallelReadMediaExchange())).toBe(true);
    // …and the interleaved shape the loop used to produce does NOT satisfy it, so this discriminates.
    const interleaved: LlmMessage[] = [
      { role: 'tool', content: [{ type: 'tool_result', toolCallId: 'c1', result: 'a' }] },
      { role: 'user', content: [{ type: 'text', text: 'attachment' }] },
      { role: 'tool', content: [{ type: 'tool_result', toolCallId: 'c2', result: 'b' }] },
    ];
    expect(toolResultsContiguous(interleaved)).toBe(false);
  });

  it('Anthropic: the resolved image lands on the wire', async () => {
    let sent: unknown;
    const adapter = createAnthropicAdapter({
      fetch: (_input, init) => {
        sent = parseJsonBody(init);
        return Promise.resolve(
          new Response(
            JSON.stringify({
              id: 'm',
              type: 'message',
              role: 'assistant',
              model: 'claude-opus-4-8',
              content: [{ type: 'text', text: 'ok' }],
              stop_reason: 'end_turn',
              usage: { input_tokens: 1, output_tokens: 1 },
            }),
            { status: 200, headers: { 'content-type': 'application/json' } },
          ),
        );
      },
      maxRetries: 0,
    });
    await sendThroughChain(adapter, 'claude-opus-4-8');
    expect(containsImage(sent)).toBe(true);

    // …and the PARALLEL shape lowers too, with both images present.
    await sendThroughChain(adapter, 'claude-opus-4-8', parallelReadMediaExchange());
    expect(containsImage(sent)).toBe(true);
  });

  it('OpenAI: the resolved image lands on the wire (NOT filtered out with the tool message)', async () => {
    let sent: unknown;
    const adapter = createOpenAiAdapter({
      fetch: (_input, init) => {
        sent = parseJsonBody(init);
        return Promise.resolve(
          new Response(
            JSON.stringify({
              id: 'c',
              object: 'chat.completion',
              created: 0,
              model: 'gpt-5.5',
              choices: [
                {
                  index: 0,
                  message: { role: 'assistant', content: 'ok', refusal: null },
                  finish_reason: 'stop',
                  logprobs: null,
                },
              ],
              usage: { prompt_tokens: 1, completion_tokens: 1, total_tokens: 2 },
            }),
            { status: 200, headers: { 'content-type': 'application/json' } },
          ),
        );
      },
      maxRetries: 0,
    });
    await sendThroughChain(adapter, 'gpt-5.5');
    expect(containsImage(sent)).toBe(true);
  });

  it('Gemini: the resolved image lands on the wire', async () => {
    // The `@google/genai` SDK exposes no `fetch` hook, so the Gemini adapter isolates the network behind
    // an injected `GeminiTransport` instead — the request it hands the transport IS the wire payload.
    let sent: unknown;
    const unused = (): Promise<never> => Promise.reject(new Error('unused'));
    const adapter = createGeminiAdapter({
      transport: {
        generate: (request) => {
          sent = request;
          return Promise.resolve({
            candidates: [
              { content: { role: 'model', parts: [{ text: 'ok' }] }, finishReason: 'STOP' },
            ],
            usageMetadata: { promptTokenCount: 1, candidatesTokenCount: 1 },
          });
        },
        stream: unused,
        listModels: unused,
        generateImages: unused,
        generateVideos: unused,
        pollVideo: unused,
      },
    });
    await sendThroughChain(adapter, 'gemini-3-pro');
    expect(containsImage(sent)).toBe(true);
  });
});
