// GENERATED FILE — DO NOT EDIT BY HAND. Run `pnpm sync:models`.
//
// The model-catalog snapshot (ADR-0071). Source: https://models.dev/api.json
// Catalog SHA-256: a40975f15ee02a1ecc52383e3636ba9c89fefcf1f0adf7c941107cc5800e1b91
// Models: 80
//
// This SHIPS IN THE BINARY on purpose. The cost cap (ADR-0028) is a safety control, and a safety control that
// only works when a third-party host is reachable is not one — so every model here is priced offline, on first
// run, with no network at all. The optional refresh (ADR-0071 §4) is default-OFF and can only ADD to this floor.
//
// Reviewing a diff here is reviewing a MONEY change. A price that moves on a model we already ship fails the
// sync deliberately (`--accept-price-changes` to take it) — because a rate that silently halves also silently
// halves the cap's protection.

import type { CatalogSnapshot } from './catalog-model.js';

export const CATALOG_SNAPSHOT: CatalogSnapshot = {
  'claude-fable-5': {
    provider: 'anthropic',
    modelId: 'claude-fable-5',
    displayName: 'Claude Fable 5',
    contextWindowTokens: 1000000,
    maxOutputTokens: 128000,
    inputPerMtokMicrocents: 1000000000,
    outputPerMtokMicrocents: 5000000000,
    cachedInputPerMtokMicrocents: 100000000,
    cacheWritePerMtokMicrocents: 1250000000,
    reasoning: { effortValues: ['low', 'medium', 'high', 'xhigh', 'max'] },
    requestCapabilities: { temperature: false },
    inputModalities: ['text', 'image', 'pdf'],
    outputModalities: ['text'],
    description: 'Claude model for creative writing, analysis, and controlled agent workflows',
  },
  'claude-haiku-4-5': {
    provider: 'anthropic',
    modelId: 'claude-haiku-4-5',
    displayName: 'Claude Haiku 4.5 (latest)',
    contextWindowTokens: 200000,
    maxOutputTokens: 64000,
    inputPerMtokMicrocents: 100000000,
    outputPerMtokMicrocents: 500000000,
    cachedInputPerMtokMicrocents: 10000000,
    cacheWritePerMtokMicrocents: 125000000,
    reasoning: { budgetTokens: { min: 1024 } },
    inputModalities: ['text', 'image', 'pdf'],
    outputModalities: ['text'],
    knowledgeCutoff: '2025-02-28',
    description: 'Fast Claude lane for lightweight agents, office tasks, and responsive chat',
  },
  'claude-haiku-4-5-20251001': {
    provider: 'anthropic',
    modelId: 'claude-haiku-4-5-20251001',
    displayName: 'Claude Haiku 4.5',
    contextWindowTokens: 200000,
    maxOutputTokens: 64000,
    inputPerMtokMicrocents: 100000000,
    outputPerMtokMicrocents: 500000000,
    cachedInputPerMtokMicrocents: 10000000,
    cacheWritePerMtokMicrocents: 125000000,
    reasoning: { budgetTokens: { min: 1024 } },
    inputModalities: ['text', 'image', 'pdf'],
    outputModalities: ['text'],
    knowledgeCutoff: '2025-02-28',
    description:
      'Fast Claude model for responsive assistance, classification, and lightweight agents',
  },
  'claude-opus-4-1': {
    provider: 'anthropic',
    modelId: 'claude-opus-4-1',
    displayName: 'Claude Opus 4.1 (latest)',
    contextWindowTokens: 200000,
    maxOutputTokens: 32000,
    inputPerMtokMicrocents: 1500000000,
    outputPerMtokMicrocents: 7500000000,
    cachedInputPerMtokMicrocents: 150000000,
    cacheWritePerMtokMicrocents: 1875000000,
    reasoning: { budgetTokens: { min: 1024 } },
    inputModalities: ['text', 'image', 'pdf'],
    outputModalities: ['text'],
    knowledgeCutoff: '2025-03-31',
    description: 'Flagship Claude model for deep reasoning, coding, and long-horizon agents',
  },
  'claude-opus-4-1-20250805': {
    provider: 'anthropic',
    modelId: 'claude-opus-4-1-20250805',
    displayName: 'Claude Opus 4.1',
    contextWindowTokens: 200000,
    maxOutputTokens: 32000,
    inputPerMtokMicrocents: 1500000000,
    outputPerMtokMicrocents: 7500000000,
    cachedInputPerMtokMicrocents: 150000000,
    cacheWritePerMtokMicrocents: 1875000000,
    reasoning: { budgetTokens: { min: 1024 } },
    inputModalities: ['text', 'image', 'pdf'],
    outputModalities: ['text'],
    knowledgeCutoff: '2025-03-31',
    description: 'Flagship Claude model for deep reasoning, coding, and long-horizon agents',
  },
  'claude-opus-4-5': {
    provider: 'anthropic',
    modelId: 'claude-opus-4-5',
    displayName: 'Claude Opus 4.5 (latest)',
    contextWindowTokens: 200000,
    maxOutputTokens: 64000,
    inputPerMtokMicrocents: 500000000,
    outputPerMtokMicrocents: 2500000000,
    cachedInputPerMtokMicrocents: 50000000,
    cacheWritePerMtokMicrocents: 625000000,
    reasoning: { effortValues: ['low', 'medium', 'high'], budgetTokens: { min: 1024 } },
    inputModalities: ['text', 'image', 'pdf'],
    outputModalities: ['text'],
    knowledgeCutoff: '2025-05',
    description: 'Flagship Claude model for deep reasoning, coding, and long-horizon agents',
  },
  'claude-opus-4-5-20251101': {
    provider: 'anthropic',
    modelId: 'claude-opus-4-5-20251101',
    displayName: 'Claude Opus 4.5',
    contextWindowTokens: 200000,
    maxOutputTokens: 64000,
    inputPerMtokMicrocents: 500000000,
    outputPerMtokMicrocents: 2500000000,
    cachedInputPerMtokMicrocents: 50000000,
    cacheWritePerMtokMicrocents: 625000000,
    reasoning: { effortValues: ['low', 'medium', 'high'], budgetTokens: { min: 1024 } },
    inputModalities: ['text', 'image', 'pdf'],
    outputModalities: ['text'],
    knowledgeCutoff: '2025-05',
    description: 'Flagship Claude model for deep reasoning, coding, and long-horizon agents',
  },
  'claude-opus-4-6': {
    provider: 'anthropic',
    modelId: 'claude-opus-4-6',
    displayName: 'Claude Opus 4.6',
    contextWindowTokens: 1000000,
    maxOutputTokens: 128000,
    inputPerMtokMicrocents: 500000000,
    outputPerMtokMicrocents: 2500000000,
    cachedInputPerMtokMicrocents: 50000000,
    cacheWritePerMtokMicrocents: 625000000,
    reasoning: { effortValues: ['low', 'medium', 'high', 'max'], budgetTokens: { min: 1024 } },
    inputModalities: ['text', 'image', 'pdf'],
    outputModalities: ['text'],
    knowledgeCutoff: '2025-05-31',
    description: 'High-end Claude for difficult coding, planning, and slower expert reasoning',
  },
  'claude-opus-4-7': {
    provider: 'anthropic',
    modelId: 'claude-opus-4-7',
    displayName: 'Claude Opus 4.7',
    contextWindowTokens: 1000000,
    maxOutputTokens: 128000,
    inputPerMtokMicrocents: 500000000,
    outputPerMtokMicrocents: 2500000000,
    cachedInputPerMtokMicrocents: 50000000,
    cacheWritePerMtokMicrocents: 625000000,
    reasoning: { effortValues: ['low', 'medium', 'high', 'xhigh', 'max'] },
    requestCapabilities: { temperature: false },
    inputModalities: ['text', 'image', 'pdf'],
    outputModalities: ['text'],
    knowledgeCutoff: '2026-01-31',
    description: 'Stronger Opus tier for advanced software work and high-stakes reasoning',
  },
  'claude-opus-4-8': {
    provider: 'anthropic',
    modelId: 'claude-opus-4-8',
    displayName: 'Claude Opus 4.8',
    contextWindowTokens: 1000000,
    maxOutputTokens: 128000,
    inputPerMtokMicrocents: 500000000,
    outputPerMtokMicrocents: 2500000000,
    cachedInputPerMtokMicrocents: 50000000,
    cacheWritePerMtokMicrocents: 625000000,
    reasoning: { effortValues: ['low', 'medium', 'high', 'xhigh', 'max'] },
    requestCapabilities: { temperature: false },
    inputModalities: ['text', 'image', 'pdf'],
    outputModalities: ['text'],
    knowledgeCutoff: '2026-01',
    description: 'Top Claude Opus tier for the hardest reasoning, coding, and long-horizon agents',
  },
  'claude-opus-5': {
    provider: 'anthropic',
    modelId: 'claude-opus-5',
    displayName: 'Claude Opus 5',
    contextWindowTokens: 1000000,
    maxOutputTokens: 128000,
    inputPerMtokMicrocents: 500000000,
    outputPerMtokMicrocents: 2500000000,
    cachedInputPerMtokMicrocents: 50000000,
    cacheWritePerMtokMicrocents: 625000000,
    reasoning: { effortValues: ['low', 'medium', 'high', 'xhigh', 'max'] },
    requestCapabilities: { temperature: false },
    inputModalities: ['text', 'image', 'pdf'],
    outputModalities: ['text'],
    knowledgeCutoff: '2026-05',
    description: 'Strongest Claude Opus model for coding, agents, and professional work',
  },
  'claude-sonnet-4-5': {
    provider: 'anthropic',
    modelId: 'claude-sonnet-4-5',
    displayName: 'Claude Sonnet 4.5 (latest)',
    contextWindowTokens: 1000000,
    maxOutputTokens: 64000,
    inputPerMtokMicrocents: 300000000,
    outputPerMtokMicrocents: 1500000000,
    cachedInputPerMtokMicrocents: 30000000,
    cacheWritePerMtokMicrocents: 375000000,
    reasoning: { budgetTokens: { min: 1024 } },
    inputModalities: ['text', 'image', 'pdf'],
    outputModalities: ['text'],
    knowledgeCutoff: '2025-07-31',
    description: 'Balanced Claude model for coding, analysis, agent workflows, and cost control',
  },
  'claude-sonnet-4-5-20250929': {
    provider: 'anthropic',
    modelId: 'claude-sonnet-4-5-20250929',
    displayName: 'Claude Sonnet 4.5',
    contextWindowTokens: 1000000,
    maxOutputTokens: 64000,
    inputPerMtokMicrocents: 300000000,
    outputPerMtokMicrocents: 1500000000,
    cachedInputPerMtokMicrocents: 30000000,
    cacheWritePerMtokMicrocents: 375000000,
    reasoning: { budgetTokens: { min: 1024 } },
    inputModalities: ['text', 'image', 'pdf'],
    outputModalities: ['text'],
    knowledgeCutoff: '2025-07-31',
    description: 'Balanced Claude model for coding, analysis, agent workflows, and cost control',
  },
  'claude-sonnet-4-6': {
    provider: 'anthropic',
    modelId: 'claude-sonnet-4-6',
    displayName: 'Claude Sonnet 4.6',
    contextWindowTokens: 1000000,
    maxOutputTokens: 128000,
    inputPerMtokMicrocents: 300000000,
    outputPerMtokMicrocents: 1500000000,
    cachedInputPerMtokMicrocents: 30000000,
    cacheWritePerMtokMicrocents: 375000000,
    reasoning: { effortValues: ['low', 'medium', 'high', 'max'], budgetTokens: { min: 1024 } },
    inputModalities: ['text', 'image', 'pdf'],
    outputModalities: ['text'],
    knowledgeCutoff: '2025-08-31',
    description:
      'Claude workhorse for coding agents, careful analysis, and production cost control',
  },
  'claude-sonnet-5': {
    provider: 'anthropic',
    modelId: 'claude-sonnet-5',
    displayName: 'Claude Sonnet 5',
    contextWindowTokens: 1000000,
    maxOutputTokens: 128000,
    inputPerMtokMicrocents: 200000000,
    outputPerMtokMicrocents: 1000000000,
    cachedInputPerMtokMicrocents: 20000000,
    cacheWritePerMtokMicrocents: 250000000,
    reasoning: { toggle: true, effortValues: ['low', 'medium', 'high', 'xhigh', 'max'] },
    requestCapabilities: { temperature: false },
    inputModalities: ['text', 'image', 'pdf'],
    outputModalities: ['text'],
    knowledgeCutoff: '2026-01-31',
    description: 'Everyday Claude agent model for coding, planning, browsing, and general work',
  },
  'deep-research-max-preview-04-2026': {
    provider: 'gemini',
    modelId: 'deep-research-max-preview-04-2026',
    displayName: 'Deep Research Max Preview (Apr-21-2026)',
    contextWindowTokens: 131072,
    maxOutputTokens: 65536,
    inputPerMtokMicrocents: 200000000,
    outputPerMtokMicrocents: 1200000000,
    cachedInputPerMtokMicrocents: 20000000,
    contextTiers: [
      {
        aboveContextTokens: 200000,
        inputPerMtokMicrocents: 400000000,
        outputPerMtokMicrocents: 1800000000,
        cachedInputPerMtokMicrocents: 40000000,
      },
    ],
    reasoning: {},
    inputModalities: ['text', 'image', 'video', 'audio', 'pdf'],
    outputModalities: ['text', 'image'],
    knowledgeCutoff: '2025-01',
    description:
      'Maximum-comprehensiveness agentic researcher for multi-step investigation, synthesis, and cited reports',
  },
  'deep-research-preview-04-2026': {
    provider: 'gemini',
    modelId: 'deep-research-preview-04-2026',
    displayName: 'Deep Research Preview (Apr-21-2026)',
    contextWindowTokens: 131072,
    maxOutputTokens: 65536,
    inputPerMtokMicrocents: 200000000,
    outputPerMtokMicrocents: 1200000000,
    cachedInputPerMtokMicrocents: 20000000,
    contextTiers: [
      {
        aboveContextTokens: 200000,
        inputPerMtokMicrocents: 400000000,
        outputPerMtokMicrocents: 1800000000,
        cachedInputPerMtokMicrocents: 40000000,
      },
    ],
    reasoning: {},
    inputModalities: ['text', 'image', 'video', 'audio', 'pdf'],
    outputModalities: ['text', 'image'],
    knowledgeCutoff: '2025-01',
    description: 'Agentic model for autonomous multi-step research, synthesis, and cited reports',
  },
  'deepseek-chat': {
    provider: 'deepseek',
    modelId: 'deepseek-chat',
    displayName: 'DeepSeek Chat',
    contextWindowTokens: 1000000,
    maxOutputTokens: 384000,
    inputPerMtokMicrocents: 14000000,
    outputPerMtokMicrocents: 28000000,
    cachedInputPerMtokMicrocents: 280000,
    inputModalities: ['text'],
    outputModalities: ['text'],
    knowledgeCutoff: '2025-09',
    description: 'DeepSeek chat model for instruction following, coding, and analysis',
  },
  'deepseek-reasoner': {
    provider: 'deepseek',
    modelId: 'deepseek-reasoner',
    displayName: 'DeepSeek Reasoner',
    contextWindowTokens: 1000000,
    maxOutputTokens: 384000,
    inputPerMtokMicrocents: 14000000,
    outputPerMtokMicrocents: 28000000,
    cachedInputPerMtokMicrocents: 280000,
    reasoning: {},
    inputModalities: ['text'],
    outputModalities: ['text'],
    knowledgeCutoff: '2025-09',
    description: 'DeepSeek reasoning model for multi-step analysis, math, coding, and tools',
  },
  'deepseek-v4-flash': {
    provider: 'deepseek',
    modelId: 'deepseek-v4-flash',
    displayName: 'DeepSeek V4 Flash',
    contextWindowTokens: 1000000,
    maxOutputTokens: 384000,
    inputPerMtokMicrocents: 14000000,
    outputPerMtokMicrocents: 28000000,
    cachedInputPerMtokMicrocents: 280000,
    reasoning: { toggle: true, effortValues: ['high', 'max'] },
    requestCapabilities: { attachment: false },
    inputModalities: ['text'],
    outputModalities: ['text'],
    knowledgeCutoff: '2025-05',
    description: 'Fast DeepSeek V4 lane for economical reasoning, coding, and long-context work',
  },
  'deepseek-v4-pro': {
    provider: 'deepseek',
    modelId: 'deepseek-v4-pro',
    displayName: 'DeepSeek V4 Pro',
    contextWindowTokens: 1000000,
    maxOutputTokens: 384000,
    inputPerMtokMicrocents: 43500000,
    outputPerMtokMicrocents: 87000000,
    cachedInputPerMtokMicrocents: 362500,
    reasoning: { toggle: true, effortValues: ['high', 'max'] },
    requestCapabilities: { attachment: false },
    inputModalities: ['text'],
    outputModalities: ['text'],
    knowledgeCutoff: '2025-05',
    description: 'Open MoE flagship with million-token context for coding and long agent runs',
  },
  'gemini-2.0-flash': {
    provider: 'gemini',
    modelId: 'gemini-2.0-flash',
    displayName: 'Gemini 2.0 Flash',
    contextWindowTokens: 1048576,
    maxOutputTokens: 8192,
    inputPerMtokMicrocents: 10000000,
    outputPerMtokMicrocents: 40000000,
    cachedInputPerMtokMicrocents: 2500000,
    inputModalities: ['text', 'image', 'audio', 'video', 'pdf'],
    outputModalities: ['text'],
    knowledgeCutoff: '2024-06',
    description: 'Earlier Gemini Flash workhorse for responsive multimodal apps and tool use',
  },
  'gemini-2.0-flash-lite': {
    provider: 'gemini',
    modelId: 'gemini-2.0-flash-lite',
    displayName: 'Gemini 2.0 Flash-Lite',
    contextWindowTokens: 1048576,
    maxOutputTokens: 8192,
    inputPerMtokMicrocents: 7500000,
    outputPerMtokMicrocents: 30000000,
    inputModalities: ['text', 'image', 'audio', 'video', 'pdf'],
    outputModalities: ['text'],
    knowledgeCutoff: '2024-06',
    description: 'Legacy model retained for compatibility with older integrations',
  },
  'gemini-2.5-computer-use-preview-10-2025': {
    provider: 'gemini',
    modelId: 'gemini-2.5-computer-use-preview-10-2025',
    displayName: 'Gemini 2.5 Computer Use Preview 10-2025',
    contextWindowTokens: 131072,
    maxOutputTokens: 65536,
    inputPerMtokMicrocents: 125000000,
    outputPerMtokMicrocents: 1000000000,
    contextTiers: [
      {
        aboveContextTokens: 200000,
        inputPerMtokMicrocents: 250000000,
        outputPerMtokMicrocents: 1500000000,
      },
    ],
    reasoning: {},
    inputModalities: ['text', 'image'],
    outputModalities: ['text'],
    knowledgeCutoff: '2025-01',
    description: 'Specialized Gemini 2.5 model for browser-control agents that automate UI tasks',
  },
  'gemini-2.5-flash': {
    provider: 'gemini',
    modelId: 'gemini-2.5-flash',
    displayName: 'Gemini 2.5 Flash',
    contextWindowTokens: 1048576,
    maxOutputTokens: 65536,
    inputPerMtokMicrocents: 30000000,
    outputPerMtokMicrocents: 250000000,
    cachedInputPerMtokMicrocents: 3000000,
    reasoning: { toggle: true, budgetTokens: { min: 0, max: 24576 } },
    inputModalities: ['text', 'image', 'audio', 'video', 'pdf'],
    outputModalities: ['text'],
    knowledgeCutoff: '2025-01',
    description: 'Fast Gemini workhorse for multimodal apps where latency and price matter',
  },
  'gemini-2.5-flash-lite': {
    provider: 'gemini',
    modelId: 'gemini-2.5-flash-lite',
    displayName: 'Gemini 2.5 Flash-Lite',
    contextWindowTokens: 1048576,
    maxOutputTokens: 65536,
    inputPerMtokMicrocents: 10000000,
    outputPerMtokMicrocents: 40000000,
    cachedInputPerMtokMicrocents: 1000000,
    reasoning: { toggle: true, budgetTokens: { min: 512, max: 24576 } },
    inputModalities: ['text', 'image', 'audio', 'video', 'pdf'],
    outputModalities: ['text'],
    knowledgeCutoff: '2025-01',
    description: 'Lean Gemini 2.5 lane for cheap multimodal traffic and quick agents',
  },
  'gemini-2.5-pro': {
    provider: 'gemini',
    modelId: 'gemini-2.5-pro',
    displayName: 'Gemini 2.5 Pro',
    contextWindowTokens: 1048576,
    maxOutputTokens: 65536,
    inputPerMtokMicrocents: 125000000,
    outputPerMtokMicrocents: 1000000000,
    cachedInputPerMtokMicrocents: 12500000,
    contextTiers: [
      {
        aboveContextTokens: 200000,
        inputPerMtokMicrocents: 250000000,
        outputPerMtokMicrocents: 1500000000,
        cachedInputPerMtokMicrocents: 25000000,
      },
    ],
    reasoning: { budgetTokens: { min: 128, max: 32768 } },
    inputModalities: ['text', 'image', 'audio', 'video', 'pdf'],
    outputModalities: ['text'],
    knowledgeCutoff: '2025-01',
    description: "Google's proven reasoning model for coding, math, and multimodal analysis",
  },
  'gemini-3-flash-preview': {
    provider: 'gemini',
    modelId: 'gemini-3-flash-preview',
    displayName: 'Gemini 3 Flash Preview',
    contextWindowTokens: 1048576,
    maxOutputTokens: 65536,
    inputPerMtokMicrocents: 50000000,
    outputPerMtokMicrocents: 300000000,
    cachedInputPerMtokMicrocents: 5000000,
    reasoning: { effortValues: ['minimal', 'low', 'medium', 'high'] },
    inputModalities: ['text', 'image', 'video', 'audio', 'pdf'],
    outputModalities: ['text'],
    knowledgeCutoff: '2025-01',
    description:
      'New Gemini flash lane bringing frontier-style multimodal reasoning to cheaper runs',
  },
  'gemini-3-pro-preview': {
    provider: 'gemini',
    modelId: 'gemini-3-pro-preview',
    displayName: 'Gemini 3 Pro Preview',
    contextWindowTokens: 1048576,
    maxOutputTokens: 65536,
    inputPerMtokMicrocents: 200000000,
    outputPerMtokMicrocents: 1200000000,
    cachedInputPerMtokMicrocents: 20000000,
    contextTiers: [
      {
        aboveContextTokens: 200000,
        inputPerMtokMicrocents: 400000000,
        outputPerMtokMicrocents: 1800000000,
        cachedInputPerMtokMicrocents: 40000000,
      },
    ],
    reasoning: { effortValues: ['low', 'high'] },
    inputModalities: ['text', 'image', 'video', 'audio', 'pdf'],
    outputModalities: ['text'],
    knowledgeCutoff: '2025-01',
    description:
      'Preview Gemini flagship for complex reasoning, coding, and rich multimodal prompts',
  },
  'gemini-3.1-flash-lite': {
    provider: 'gemini',
    modelId: 'gemini-3.1-flash-lite',
    displayName: 'Gemini 3.1 Flash Lite',
    contextWindowTokens: 1048576,
    maxOutputTokens: 65536,
    inputPerMtokMicrocents: 25000000,
    outputPerMtokMicrocents: 150000000,
    cachedInputPerMtokMicrocents: 2500000,
    reasoning: { effortValues: ['minimal', 'low', 'medium', 'high'] },
    inputModalities: ['text', 'image', 'video', 'audio', 'pdf'],
    outputModalities: ['text'],
    knowledgeCutoff: '2025-01',
    description: 'Low-latency Gemini model for high-volume multimodal and agent workloads',
  },
  'gemini-3.1-flash-lite-preview': {
    provider: 'gemini',
    modelId: 'gemini-3.1-flash-lite-preview',
    displayName: 'Gemini 3.1 Flash Lite Preview',
    contextWindowTokens: 1048576,
    maxOutputTokens: 65536,
    inputPerMtokMicrocents: 25000000,
    outputPerMtokMicrocents: 150000000,
    cachedInputPerMtokMicrocents: 2500000,
    reasoning: { effortValues: ['minimal', 'low', 'medium', 'high'] },
    inputModalities: ['text', 'image', 'video', 'audio', 'pdf'],
    outputModalities: ['text'],
    knowledgeCutoff: '2025-01',
    description: 'Legacy model retained for compatibility with older integrations',
  },
  'gemini-3.1-flash-live-preview': {
    provider: 'gemini',
    modelId: 'gemini-3.1-flash-live-preview',
    displayName: 'Gemini 3.1 Flash Live Preview',
    contextWindowTokens: 131072,
    maxOutputTokens: 65536,
    inputPerMtokMicrocents: 75000000,
    outputPerMtokMicrocents: 450000000,
    reasoning: { effortValues: ['minimal', 'low', 'medium', 'high'] },
    requestCapabilities: { structuredOutput: false },
    inputModalities: ['text', 'image', 'video', 'audio'],
    outputModalities: ['text', 'audio'],
    knowledgeCutoff: '2025-01',
    description:
      'High-quality, low-latency Live API model for real-time dialogue and voice-first AI applications',
  },
  'gemini-3.1-pro-preview': {
    provider: 'gemini',
    modelId: 'gemini-3.1-pro-preview',
    displayName: 'Gemini 3.1 Pro Preview',
    contextWindowTokens: 1048576,
    maxOutputTokens: 65536,
    inputPerMtokMicrocents: 200000000,
    outputPerMtokMicrocents: 1200000000,
    cachedInputPerMtokMicrocents: 20000000,
    contextTiers: [
      {
        aboveContextTokens: 200000,
        inputPerMtokMicrocents: 400000000,
        outputPerMtokMicrocents: 1800000000,
        cachedInputPerMtokMicrocents: 40000000,
      },
    ],
    reasoning: { effortValues: ['low', 'medium', 'high'] },
    inputModalities: ['text', 'image', 'video', 'audio', 'pdf'],
    outputModalities: ['text'],
    knowledgeCutoff: '2025-01',
    description: 'Reasoning-first Gemini preview for agentic coding and complex problem solving',
  },
  'gemini-3.1-pro-preview-customtools': {
    provider: 'gemini',
    modelId: 'gemini-3.1-pro-preview-customtools',
    displayName: 'Gemini 3.1 Pro Preview Custom Tools',
    contextWindowTokens: 1048576,
    maxOutputTokens: 65536,
    inputPerMtokMicrocents: 200000000,
    outputPerMtokMicrocents: 1200000000,
    cachedInputPerMtokMicrocents: 20000000,
    contextTiers: [
      {
        aboveContextTokens: 200000,
        inputPerMtokMicrocents: 400000000,
        outputPerMtokMicrocents: 1800000000,
        cachedInputPerMtokMicrocents: 40000000,
      },
    ],
    reasoning: { effortValues: ['low', 'medium', 'high'] },
    inputModalities: ['text', 'image', 'video', 'audio', 'pdf'],
    outputModalities: ['text'],
    knowledgeCutoff: '2025-01',
    description: 'Advanced Gemini model for complex reasoning, coding, and multimodal analysis',
  },
  'gemini-3.5-flash': {
    provider: 'gemini',
    modelId: 'gemini-3.5-flash',
    displayName: 'Gemini 3.5 Flash',
    contextWindowTokens: 1048576,
    maxOutputTokens: 65536,
    inputPerMtokMicrocents: 150000000,
    outputPerMtokMicrocents: 900000000,
    cachedInputPerMtokMicrocents: 15000000,
    reasoning: { effortValues: ['minimal', 'low', 'medium', 'high'] },
    inputModalities: ['text', 'image', 'video', 'audio', 'pdf'],
    outputModalities: ['text'],
    knowledgeCutoff: '2025-01',
    description: 'Fast Gemini model balancing multimodal reasoning, tool use, and cost',
  },
  'gemini-3.5-flash-lite': {
    provider: 'gemini',
    modelId: 'gemini-3.5-flash-lite',
    displayName: 'Gemini 3.5 Flash Lite',
    contextWindowTokens: 1048576,
    maxOutputTokens: 65536,
    inputPerMtokMicrocents: 30000000,
    outputPerMtokMicrocents: 250000000,
    cachedInputPerMtokMicrocents: 3000000,
    reasoning: { effortValues: ['minimal', 'low', 'medium', 'high'] },
    inputModalities: ['text', 'image', 'video', 'audio', 'pdf'],
    outputModalities: ['text'],
    knowledgeCutoff: '2026-03',
    description: 'Fast Gemini model balancing multimodal reasoning, tool use, and cost',
  },
  'gemini-3.5-live-translate-preview': {
    provider: 'gemini',
    modelId: 'gemini-3.5-live-translate-preview',
    displayName: 'Gemini 3.5 Live Translate Preview',
    contextWindowTokens: 16384,
    maxOutputTokens: 32768,
    inputPerMtokMicrocents: 350000000,
    outputPerMtokMicrocents: 2100000000,
    requestCapabilities: { toolCall: false, attachment: false },
    inputModalities: ['audio'],
    outputModalities: ['audio', 'text'],
    knowledgeCutoff: '2025-01',
    description:
      'Low-latency audio-to-audio model for real-time speech translation across 70+ languages',
  },
  'gemini-3.6-flash': {
    provider: 'gemini',
    modelId: 'gemini-3.6-flash',
    displayName: 'Gemini 3.6 Flash',
    contextWindowTokens: 1048576,
    maxOutputTokens: 65536,
    inputPerMtokMicrocents: 150000000,
    outputPerMtokMicrocents: 750000000,
    cachedInputPerMtokMicrocents: 15000000,
    reasoning: { effortValues: ['minimal', 'low', 'medium', 'high'] },
    inputModalities: ['text', 'image', 'video', 'audio', 'pdf'],
    outputModalities: ['text'],
    knowledgeCutoff: '2026-03',
    description: 'Fast Gemini model balancing multimodal reasoning, tool use, and cost',
  },
  'gemini-flash-latest': {
    provider: 'gemini',
    modelId: 'gemini-flash-latest',
    displayName: 'Gemini Flash Latest',
    contextWindowTokens: 1048576,
    maxOutputTokens: 65536,
    inputPerMtokMicrocents: 150000000,
    outputPerMtokMicrocents: 900000000,
    cachedInputPerMtokMicrocents: 15000000,
    reasoning: { effortValues: ['minimal', 'low', 'medium', 'high'] },
    inputModalities: ['text', 'image', 'video', 'audio', 'pdf'],
    outputModalities: ['text'],
    knowledgeCutoff: '2025-01',
    description: 'Fast Gemini model balancing multimodal reasoning, tool use, and cost',
  },
  'gemini-flash-lite-latest': {
    provider: 'gemini',
    modelId: 'gemini-flash-lite-latest',
    displayName: 'Gemini Flash-Lite Latest',
    contextWindowTokens: 1048576,
    maxOutputTokens: 65536,
    inputPerMtokMicrocents: 25000000,
    outputPerMtokMicrocents: 150000000,
    cachedInputPerMtokMicrocents: 2500000,
    reasoning: { effortValues: ['minimal', 'low', 'medium', 'high'] },
    inputModalities: ['text', 'image', 'video', 'audio', 'pdf'],
    outputModalities: ['text'],
    knowledgeCutoff: '2025-01',
    description: 'Low-latency Gemini model for high-volume multimodal and agent workloads',
  },
  'gemini-omni-flash-preview': {
    provider: 'gemini',
    modelId: 'gemini-omni-flash-preview',
    displayName: 'Gemini Omni Flash Preview',
    contextWindowTokens: 131072,
    maxOutputTokens: 65536,
    inputPerMtokMicrocents: 150000000,
    outputPerMtokMicrocents: 1750000000,
    reasoning: {},
    requestCapabilities: { toolCall: false },
    inputModalities: ['text', 'image', 'video'],
    outputModalities: ['video'],
    description:
      'Video generation and editing model for fast, conversational text- and image-to-video workflows',
  },
  'gemini-robotics-er-1.6-preview': {
    provider: 'gemini',
    modelId: 'gemini-robotics-er-1.6-preview',
    displayName: 'Gemini Robotics-ER 1.6 Preview',
    contextWindowTokens: 131072,
    maxOutputTokens: 65536,
    inputPerMtokMicrocents: 100000000,
    outputPerMtokMicrocents: 500000000,
    reasoning: { toggle: true, budgetTokens: { min: 0 } },
    inputModalities: ['text', 'image', 'video', 'audio'],
    outputModalities: ['text'],
    knowledgeCutoff: '2025-01',
    description:
      'Vision-language model for embodied reasoning: spatial understanding, task planning, and physical-world agentic robotics',
  },
  'gpt-3.5-turbo': {
    provider: 'openai',
    modelId: 'gpt-3.5-turbo',
    displayName: 'GPT-3.5-turbo',
    contextWindowTokens: 16385,
    maxOutputTokens: 4096,
    inputPerMtokMicrocents: 50000000,
    outputPerMtokMicrocents: 150000000,
    cachedInputPerMtokMicrocents: 0,
    requestCapabilities: { toolCall: false, structuredOutput: false, attachment: false },
    inputModalities: ['text'],
    outputModalities: ['text'],
    knowledgeCutoff: '2021-09-01',
    description: 'Compact GPT model for low-latency assistance and high-volume workloads',
  },
  'gpt-4': {
    provider: 'openai',
    modelId: 'gpt-4',
    displayName: 'GPT-4',
    contextWindowTokens: 8192,
    maxOutputTokens: 8192,
    inputPerMtokMicrocents: 3000000000,
    outputPerMtokMicrocents: 6000000000,
    requestCapabilities: { structuredOutput: false },
    inputModalities: ['text'],
    outputModalities: ['text'],
    knowledgeCutoff: '2023-11',
    description: 'GPT model for general reasoning, writing, coding, and tool-assisted tasks',
  },
  'gpt-4-turbo': {
    provider: 'openai',
    modelId: 'gpt-4-turbo',
    displayName: 'GPT-4 Turbo',
    contextWindowTokens: 128000,
    maxOutputTokens: 4096,
    inputPerMtokMicrocents: 1000000000,
    outputPerMtokMicrocents: 3000000000,
    requestCapabilities: { structuredOutput: false },
    inputModalities: ['text', 'image'],
    outputModalities: ['text'],
    knowledgeCutoff: '2023-12',
    description: 'Compact GPT model for low-latency assistance and high-volume workloads',
  },
  'gpt-4.1': {
    provider: 'openai',
    modelId: 'gpt-4.1',
    displayName: 'GPT-4.1',
    contextWindowTokens: 1047576,
    maxOutputTokens: 32768,
    inputPerMtokMicrocents: 200000000,
    outputPerMtokMicrocents: 800000000,
    cachedInputPerMtokMicrocents: 50000000,
    inputModalities: ['text', 'image', 'pdf'],
    outputModalities: ['text'],
    knowledgeCutoff: '2024-04',
    description: 'Long-lived GPT workhorse for coding, instruction following, and production apps',
  },
  'gpt-4.1-mini': {
    provider: 'openai',
    modelId: 'gpt-4.1-mini',
    displayName: 'GPT-4.1 mini',
    contextWindowTokens: 1047576,
    maxOutputTokens: 32768,
    inputPerMtokMicrocents: 40000000,
    outputPerMtokMicrocents: 160000000,
    cachedInputPerMtokMicrocents: 10000000,
    inputModalities: ['text', 'image', 'pdf'],
    outputModalities: ['text'],
    knowledgeCutoff: '2024-04',
    description: 'Affordable GPT-4.1 lane for fast coding help and structured extraction',
  },
  'gpt-4.1-nano': {
    provider: 'openai',
    modelId: 'gpt-4.1-nano',
    displayName: 'GPT-4.1 nano',
    contextWindowTokens: 1047576,
    maxOutputTokens: 32768,
    inputPerMtokMicrocents: 10000000,
    outputPerMtokMicrocents: 40000000,
    cachedInputPerMtokMicrocents: 2500000,
    inputModalities: ['text', 'image'],
    outputModalities: ['text'],
    knowledgeCutoff: '2024-04',
    description: 'Tiny GPT-4.1 option for classification, routing, and very high-volume tasks',
  },
  'gpt-4o': {
    provider: 'openai',
    modelId: 'gpt-4o',
    displayName: 'GPT-4o',
    contextWindowTokens: 128000,
    maxOutputTokens: 16384,
    inputPerMtokMicrocents: 250000000,
    outputPerMtokMicrocents: 1000000000,
    cachedInputPerMtokMicrocents: 125000000,
    inputModalities: ['text', 'image', 'pdf'],
    outputModalities: ['text'],
    knowledgeCutoff: '2023-09',
    description: 'Omni-era GPT for multimodal chat, practical coding, and general assistants',
  },
  'gpt-4o-2024-05-13': {
    provider: 'openai',
    modelId: 'gpt-4o-2024-05-13',
    displayName: 'GPT-4o (2024-05-13)',
    contextWindowTokens: 128000,
    maxOutputTokens: 4096,
    inputPerMtokMicrocents: 500000000,
    outputPerMtokMicrocents: 1500000000,
    inputModalities: ['text', 'image'],
    outputModalities: ['text'],
    knowledgeCutoff: '2023-09',
    description: 'GPT model for general reasoning, writing, coding, and tool-assisted tasks',
  },
  'gpt-4o-2024-08-06': {
    provider: 'openai',
    modelId: 'gpt-4o-2024-08-06',
    displayName: 'GPT-4o (2024-08-06)',
    contextWindowTokens: 128000,
    maxOutputTokens: 16384,
    inputPerMtokMicrocents: 250000000,
    outputPerMtokMicrocents: 1000000000,
    cachedInputPerMtokMicrocents: 125000000,
    inputModalities: ['text', 'image'],
    outputModalities: ['text'],
    knowledgeCutoff: '2023-09',
    description: 'GPT model for general reasoning, writing, coding, and tool-assisted tasks',
  },
  'gpt-4o-2024-11-20': {
    provider: 'openai',
    modelId: 'gpt-4o-2024-11-20',
    displayName: 'GPT-4o (2024-11-20)',
    contextWindowTokens: 128000,
    maxOutputTokens: 16384,
    inputPerMtokMicrocents: 250000000,
    outputPerMtokMicrocents: 1000000000,
    cachedInputPerMtokMicrocents: 125000000,
    inputModalities: ['text', 'image'],
    outputModalities: ['text'],
    knowledgeCutoff: '2023-09',
    description: 'GPT model for general reasoning, writing, coding, and tool-assisted tasks',
  },
  'gpt-4o-mini': {
    provider: 'openai',
    modelId: 'gpt-4o-mini',
    displayName: 'GPT-4o mini',
    contextWindowTokens: 128000,
    maxOutputTokens: 16384,
    inputPerMtokMicrocents: 15000000,
    outputPerMtokMicrocents: 60000000,
    cachedInputPerMtokMicrocents: 7500000,
    inputModalities: ['text', 'image', 'pdf'],
    outputModalities: ['text'],
    knowledgeCutoff: '2023-09',
    description: 'Small omni GPT for cheap multimodal assistance and production-scale traffic',
  },
  'gpt-5': {
    provider: 'openai',
    modelId: 'gpt-5',
    displayName: 'GPT-5',
    contextWindowTokens: 400000,
    maxOutputTokens: 128000,
    inputPerMtokMicrocents: 125000000,
    outputPerMtokMicrocents: 1000000000,
    cachedInputPerMtokMicrocents: 12500000,
    reasoning: { effortValues: ['minimal', 'low', 'medium', 'high'] },
    requestCapabilities: { temperature: false },
    inputModalities: ['text', 'image'],
    outputModalities: ['text'],
    knowledgeCutoff: '2024-09-30',
    description: 'Original GPT-5 workhorse for reasoning, coding, writing, and tool workflows',
  },
  'gpt-5-mini': {
    provider: 'openai',
    modelId: 'gpt-5-mini',
    displayName: 'GPT-5 Mini',
    contextWindowTokens: 400000,
    maxOutputTokens: 128000,
    inputPerMtokMicrocents: 25000000,
    outputPerMtokMicrocents: 200000000,
    cachedInputPerMtokMicrocents: 2500000,
    reasoning: { effortValues: ['minimal', 'low', 'medium', 'high'] },
    requestCapabilities: { temperature: false },
    inputModalities: ['text', 'image'],
    outputModalities: ['text'],
    knowledgeCutoff: '2024-05-30',
    description: 'Small GPT-5 for responsive agents, coding help, and everyday automation',
  },
  'gpt-5-nano': {
    provider: 'openai',
    modelId: 'gpt-5-nano',
    displayName: 'GPT-5 Nano',
    contextWindowTokens: 400000,
    maxOutputTokens: 128000,
    inputPerMtokMicrocents: 5000000,
    outputPerMtokMicrocents: 40000000,
    cachedInputPerMtokMicrocents: 500000,
    reasoning: { effortValues: ['minimal', 'low', 'medium', 'high'] },
    requestCapabilities: { temperature: false },
    inputModalities: ['text', 'image'],
    outputModalities: ['text'],
    knowledgeCutoff: '2024-05-30',
    description: 'Tiny GPT-5 lane for routing, extraction, classification, and bulk jobs',
  },
  'gpt-5-pro': {
    provider: 'openai',
    modelId: 'gpt-5-pro',
    displayName: 'GPT-5 Pro',
    contextWindowTokens: 400000,
    maxOutputTokens: 272000,
    inputPerMtokMicrocents: 1500000000,
    outputPerMtokMicrocents: 12000000000,
    reasoning: { effortValues: ['high'] },
    requestCapabilities: { temperature: false },
    inputModalities: ['text', 'image'],
    outputModalities: ['text'],
    knowledgeCutoff: '2024-09-30',
    description: 'Higher-accuracy GPT-5 tier for tough analysis, coding reviews, and planning',
  },
  'gpt-5.1': {
    provider: 'openai',
    modelId: 'gpt-5.1',
    displayName: 'GPT-5.1',
    contextWindowTokens: 400000,
    maxOutputTokens: 128000,
    inputPerMtokMicrocents: 125000000,
    outputPerMtokMicrocents: 1000000000,
    cachedInputPerMtokMicrocents: 12500000,
    reasoning: { effortValues: ['none', 'low', 'medium', 'high'] },
    requestCapabilities: { temperature: false },
    inputModalities: ['text', 'image'],
    outputModalities: ['text'],
    knowledgeCutoff: '2024-09-30',
    description: 'Sharper GPT-5 generation for coding, product work, and tool-assisted tasks',
  },
  'gpt-5.2': {
    provider: 'openai',
    modelId: 'gpt-5.2',
    displayName: 'GPT-5.2',
    contextWindowTokens: 400000,
    maxOutputTokens: 128000,
    inputPerMtokMicrocents: 175000000,
    outputPerMtokMicrocents: 1400000000,
    cachedInputPerMtokMicrocents: 17500000,
    reasoning: { effortValues: ['none', 'low', 'medium', 'high', 'xhigh'] },
    requestCapabilities: { temperature: false },
    inputModalities: ['text', 'image'],
    outputModalities: ['text'],
    knowledgeCutoff: '2025-08-31',
    description:
      'Reliable GPT generation for broad coding, writing, and tool-assisted product work',
  },
  'gpt-5.2-chat-latest': {
    provider: 'openai',
    modelId: 'gpt-5.2-chat-latest',
    displayName: 'GPT-5.2 Chat',
    contextWindowTokens: 128000,
    maxOutputTokens: 16384,
    inputPerMtokMicrocents: 175000000,
    outputPerMtokMicrocents: 1400000000,
    cachedInputPerMtokMicrocents: 17500000,
    reasoning: { effortValues: ['medium'] },
    requestCapabilities: { temperature: false },
    inputModalities: ['text', 'image'],
    outputModalities: ['text'],
    knowledgeCutoff: '2025-08-31',
    description: 'Chat-tuned GPT model for conversational assistance, writing, and tool workflows',
  },
  'gpt-5.2-pro': {
    provider: 'openai',
    modelId: 'gpt-5.2-pro',
    displayName: 'GPT-5.2 Pro',
    contextWindowTokens: 400000,
    maxOutputTokens: 128000,
    inputPerMtokMicrocents: 2100000000,
    outputPerMtokMicrocents: 16800000000,
    reasoning: { effortValues: ['medium', 'high', 'xhigh'] },
    requestCapabilities: { temperature: false, structuredOutput: false },
    inputModalities: ['text', 'image'],
    outputModalities: ['text'],
    knowledgeCutoff: '2025-08-31',
    description: 'Higher-accuracy GPT-5.2 variant for tougher reasoning and review workflows',
  },
  'gpt-5.3-chat-latest': {
    provider: 'openai',
    modelId: 'gpt-5.3-chat-latest',
    displayName: 'GPT-5.3 Chat (latest)',
    contextWindowTokens: 128000,
    maxOutputTokens: 16384,
    inputPerMtokMicrocents: 175000000,
    outputPerMtokMicrocents: 1400000000,
    cachedInputPerMtokMicrocents: 17500000,
    inputModalities: ['text', 'image'],
    outputModalities: ['text'],
    knowledgeCutoff: '2025-08-31',
    description: 'Chat-tuned GPT model for conversational assistance, writing, and tool workflows',
  },
  'gpt-5.3-codex': {
    provider: 'openai',
    modelId: 'gpt-5.3-codex',
    displayName: 'GPT-5.3 Codex',
    contextWindowTokens: 400000,
    maxOutputTokens: 128000,
    inputPerMtokMicrocents: 175000000,
    outputPerMtokMicrocents: 1400000000,
    cachedInputPerMtokMicrocents: 17500000,
    reasoning: { effortValues: ['none', 'low', 'medium', 'high', 'xhigh'] },
    requestCapabilities: { temperature: false },
    inputModalities: ['text', 'image', 'pdf'],
    outputModalities: ['text'],
    knowledgeCutoff: '2025-08-31',
    description:
      'Coding-optimized GPT model for repository edits, reviews, and agentic software work',
  },
  'gpt-5.3-codex-spark': {
    provider: 'openai',
    modelId: 'gpt-5.3-codex-spark',
    displayName: 'GPT-5.3 Codex Spark',
    contextWindowTokens: 128000,
    maxOutputTokens: 32000,
    inputPerMtokMicrocents: 175000000,
    outputPerMtokMicrocents: 1400000000,
    cachedInputPerMtokMicrocents: 17500000,
    reasoning: { effortValues: ['none', 'low', 'medium', 'high', 'xhigh'] },
    requestCapabilities: { temperature: false },
    inputModalities: ['text', 'image', 'pdf'],
    outputModalities: ['text'],
    knowledgeCutoff: '2025-08-31',
    description:
      'Coding-optimized GPT model for repository edits, reviews, and agentic software work',
  },
  'gpt-5.4': {
    provider: 'openai',
    modelId: 'gpt-5.4',
    displayName: 'GPT-5.4',
    contextWindowTokens: 1050000,
    maxOutputTokens: 128000,
    inputPerMtokMicrocents: 250000000,
    outputPerMtokMicrocents: 1500000000,
    cachedInputPerMtokMicrocents: 25000000,
    contextTiers: [
      {
        aboveContextTokens: 272000,
        inputPerMtokMicrocents: 500000000,
        outputPerMtokMicrocents: 2250000000,
        cachedInputPerMtokMicrocents: 50000000,
      },
    ],
    reasoning: { effortValues: ['none', 'low', 'medium', 'high', 'xhigh'] },
    requestCapabilities: { temperature: false },
    inputModalities: ['text', 'image', 'pdf'],
    outputModalities: ['text'],
    knowledgeCutoff: '2025-08-31',
    description: 'Agent-ready GPT for coding and computer-use workflows at a lower cost',
  },
  'gpt-5.4-mini': {
    provider: 'openai',
    modelId: 'gpt-5.4-mini',
    displayName: 'GPT-5.4 mini',
    contextWindowTokens: 400000,
    maxOutputTokens: 128000,
    inputPerMtokMicrocents: 75000000,
    outputPerMtokMicrocents: 450000000,
    cachedInputPerMtokMicrocents: 7500000,
    reasoning: { effortValues: ['none', 'low', 'medium', 'high', 'xhigh'] },
    requestCapabilities: { temperature: false },
    inputModalities: ['text', 'image'],
    outputModalities: ['text'],
    knowledgeCutoff: '2025-08-31',
    description: 'Strong small GPT for coding subagents, quick tool use, and high-volume work',
  },
  'gpt-5.4-nano': {
    provider: 'openai',
    modelId: 'gpt-5.4-nano',
    displayName: 'GPT-5.4 nano',
    contextWindowTokens: 400000,
    maxOutputTokens: 128000,
    inputPerMtokMicrocents: 20000000,
    outputPerMtokMicrocents: 125000000,
    cachedInputPerMtokMicrocents: 2000000,
    reasoning: { effortValues: ['none', 'low', 'medium', 'high', 'xhigh'] },
    requestCapabilities: { temperature: false },
    inputModalities: ['text', 'image'],
    outputModalities: ['text'],
    knowledgeCutoff: '2025-08-31',
    description: 'Cheapest GPT-5.4 lane for simple routing, extraction, and bulk automation',
  },
  'gpt-5.4-pro': {
    provider: 'openai',
    modelId: 'gpt-5.4-pro',
    displayName: 'GPT-5.4 Pro',
    contextWindowTokens: 1050000,
    maxOutputTokens: 128000,
    inputPerMtokMicrocents: 3000000000,
    outputPerMtokMicrocents: 18000000000,
    contextTiers: [
      {
        aboveContextTokens: 272000,
        inputPerMtokMicrocents: 6000000000,
        outputPerMtokMicrocents: 27000000000,
      },
    ],
    reasoning: { effortValues: ['medium', 'high', 'xhigh'] },
    requestCapabilities: { temperature: false, structuredOutput: false },
    inputModalities: ['text', 'image'],
    outputModalities: ['text'],
    knowledgeCutoff: '2025-08-31',
    description: 'More exact GPT-5.4 tier for demanding professional reasoning and agent tasks',
  },
  'gpt-5.5': {
    provider: 'openai',
    modelId: 'gpt-5.5',
    displayName: 'GPT-5.5',
    contextWindowTokens: 1050000,
    maxOutputTokens: 128000,
    inputPerMtokMicrocents: 500000000,
    outputPerMtokMicrocents: 3000000000,
    cachedInputPerMtokMicrocents: 50000000,
    contextTiers: [
      {
        aboveContextTokens: 272000,
        inputPerMtokMicrocents: 1000000000,
        outputPerMtokMicrocents: 4500000000,
        cachedInputPerMtokMicrocents: 100000000,
      },
    ],
    reasoning: { effortValues: ['none', 'low', 'medium', 'high', 'xhigh'] },
    requestCapabilities: { temperature: false },
    inputModalities: ['text', 'image', 'pdf'],
    outputModalities: ['text'],
    knowledgeCutoff: '2025-12-01',
    description: 'Default frontier GPT for coding, computer use, research, and knowledge work',
  },
  'gpt-5.5-pro': {
    provider: 'openai',
    modelId: 'gpt-5.5-pro',
    displayName: 'GPT-5.5 Pro',
    contextWindowTokens: 1050000,
    maxOutputTokens: 128000,
    inputPerMtokMicrocents: 3000000000,
    outputPerMtokMicrocents: 18000000000,
    contextTiers: [
      {
        aboveContextTokens: 272000,
        inputPerMtokMicrocents: 6000000000,
        outputPerMtokMicrocents: 27000000000,
      },
    ],
    reasoning: { effortValues: ['medium', 'high', 'xhigh'] },
    requestCapabilities: { temperature: false },
    inputModalities: ['text', 'image', 'pdf'],
    outputModalities: ['text'],
    knowledgeCutoff: '2025-12-01',
    description: 'Highest-accuracy GPT-5.5 tier for slower, precision-heavy reasoning and coding',
  },
  'gpt-5.6': {
    provider: 'openai',
    modelId: 'gpt-5.6',
    displayName: 'GPT-5.6',
    contextWindowTokens: 1050000,
    maxOutputTokens: 128000,
    inputPerMtokMicrocents: 500000000,
    outputPerMtokMicrocents: 3000000000,
    cachedInputPerMtokMicrocents: 50000000,
    cacheWritePerMtokMicrocents: 625000000,
    contextTiers: [
      {
        aboveContextTokens: 272000,
        inputPerMtokMicrocents: 1000000000,
        outputPerMtokMicrocents: 4500000000,
        cachedInputPerMtokMicrocents: 100000000,
      },
    ],
    reasoning: { effortValues: ['none', 'low', 'medium', 'high', 'xhigh', 'max'] },
    requestCapabilities: { temperature: false },
    inputModalities: ['text', 'image', 'pdf'],
    outputModalities: ['text'],
    knowledgeCutoff: '2026-02-16',
    description:
      'Frontier GPT-5.6 model for complex professional work, coding, and agentic workflows',
  },
  'gpt-5.6-luna': {
    provider: 'openai',
    modelId: 'gpt-5.6-luna',
    displayName: 'GPT-5.6 Luna',
    contextWindowTokens: 1050000,
    maxOutputTokens: 128000,
    inputPerMtokMicrocents: 100000000,
    outputPerMtokMicrocents: 600000000,
    cachedInputPerMtokMicrocents: 10000000,
    cacheWritePerMtokMicrocents: 125000000,
    contextTiers: [
      {
        aboveContextTokens: 272000,
        inputPerMtokMicrocents: 200000000,
        outputPerMtokMicrocents: 900000000,
        cachedInputPerMtokMicrocents: 20000000,
      },
    ],
    reasoning: { effortValues: ['none', 'low', 'medium', 'high', 'xhigh', 'max'] },
    requestCapabilities: { temperature: false },
    inputModalities: ['text', 'image', 'pdf'],
    outputModalities: ['text'],
    knowledgeCutoff: '2026-02-16',
    description: 'Cost-efficient GPT-5.6 model for fast, high-volume workloads',
  },
  'gpt-5.6-sol': {
    provider: 'openai',
    modelId: 'gpt-5.6-sol',
    displayName: 'GPT-5.6 Sol',
    contextWindowTokens: 1050000,
    maxOutputTokens: 128000,
    inputPerMtokMicrocents: 500000000,
    outputPerMtokMicrocents: 3000000000,
    cachedInputPerMtokMicrocents: 50000000,
    cacheWritePerMtokMicrocents: 625000000,
    contextTiers: [
      {
        aboveContextTokens: 272000,
        inputPerMtokMicrocents: 1000000000,
        outputPerMtokMicrocents: 4500000000,
        cachedInputPerMtokMicrocents: 100000000,
      },
    ],
    reasoning: { effortValues: ['none', 'low', 'medium', 'high', 'xhigh', 'max'] },
    requestCapabilities: { temperature: false },
    inputModalities: ['text', 'image', 'pdf'],
    outputModalities: ['text'],
    knowledgeCutoff: '2026-02-16',
    description:
      'Frontier GPT-5.6 model for complex professional work, coding, and agentic workflows',
  },
  'gpt-5.6-terra': {
    provider: 'openai',
    modelId: 'gpt-5.6-terra',
    displayName: 'GPT-5.6 Terra',
    contextWindowTokens: 1050000,
    maxOutputTokens: 128000,
    inputPerMtokMicrocents: 250000000,
    outputPerMtokMicrocents: 1500000000,
    cachedInputPerMtokMicrocents: 25000000,
    cacheWritePerMtokMicrocents: 312500000,
    contextTiers: [
      {
        aboveContextTokens: 272000,
        inputPerMtokMicrocents: 500000000,
        outputPerMtokMicrocents: 2250000000,
        cachedInputPerMtokMicrocents: 50000000,
      },
    ],
    reasoning: { effortValues: ['none', 'low', 'medium', 'high', 'xhigh', 'max'] },
    requestCapabilities: { temperature: false },
    inputModalities: ['text', 'image', 'pdf'],
    outputModalities: ['text'],
    knowledgeCutoff: '2026-02-16',
    description: 'Balanced GPT-5.6 model for capable, cost-efficient everyday work',
  },
  o1: {
    provider: 'openai',
    modelId: 'o1',
    displayName: 'o1',
    contextWindowTokens: 200000,
    maxOutputTokens: 100000,
    inputPerMtokMicrocents: 1500000000,
    outputPerMtokMicrocents: 6000000000,
    cachedInputPerMtokMicrocents: 750000000,
    reasoning: { effortValues: ['low', 'medium', 'high'] },
    requestCapabilities: { temperature: false },
    inputModalities: ['text', 'image', 'pdf'],
    outputModalities: ['text'],
    knowledgeCutoff: '2023-09',
    description: 'O-series reasoning model for hard analysis, math, coding, and planning',
  },
  'o1-pro': {
    provider: 'openai',
    modelId: 'o1-pro',
    displayName: 'o1-pro',
    contextWindowTokens: 200000,
    maxOutputTokens: 100000,
    inputPerMtokMicrocents: 15000000000,
    outputPerMtokMicrocents: 60000000000,
    reasoning: { effortValues: ['low', 'medium', 'high'] },
    requestCapabilities: { temperature: false },
    inputModalities: ['text', 'image'],
    outputModalities: ['text'],
    knowledgeCutoff: '2023-09',
    description: 'O-series reasoning model for hard analysis, math, coding, and planning',
  },
  o3: {
    provider: 'openai',
    modelId: 'o3',
    displayName: 'o3',
    contextWindowTokens: 200000,
    maxOutputTokens: 100000,
    inputPerMtokMicrocents: 200000000,
    outputPerMtokMicrocents: 800000000,
    cachedInputPerMtokMicrocents: 50000000,
    reasoning: { effortValues: ['low', 'medium', 'high'] },
    requestCapabilities: { temperature: false },
    inputModalities: ['text', 'image', 'pdf'],
    outputModalities: ['text'],
    knowledgeCutoff: '2024-05',
    description: 'Deliberate o-series reasoner for hard math, coding, and multi-step analysis',
  },
  'o3-mini': {
    provider: 'openai',
    modelId: 'o3-mini',
    displayName: 'o3-mini',
    contextWindowTokens: 200000,
    maxOutputTokens: 100000,
    inputPerMtokMicrocents: 110000000,
    outputPerMtokMicrocents: 440000000,
    cachedInputPerMtokMicrocents: 55000000,
    reasoning: { effortValues: ['low', 'medium', 'high'] },
    requestCapabilities: { temperature: false, attachment: false },
    inputModalities: ['text'],
    outputModalities: ['text'],
    knowledgeCutoff: '2024-05',
    description: 'Smaller o-series reasoner for economical coding, math, and planning tasks',
  },
  'o3-pro': {
    provider: 'openai',
    modelId: 'o3-pro',
    displayName: 'o3-pro',
    contextWindowTokens: 200000,
    maxOutputTokens: 100000,
    inputPerMtokMicrocents: 2000000000,
    outputPerMtokMicrocents: 8000000000,
    reasoning: { effortValues: ['low', 'medium', 'high'] },
    requestCapabilities: { temperature: false },
    inputModalities: ['text', 'image'],
    outputModalities: ['text'],
    knowledgeCutoff: '2024-05',
    description: 'High-effort o3 tier for difficult technical reasoning and careful answers',
  },
  'o4-mini': {
    provider: 'openai',
    modelId: 'o4-mini',
    displayName: 'o4-mini',
    contextWindowTokens: 200000,
    maxOutputTokens: 100000,
    inputPerMtokMicrocents: 110000000,
    outputPerMtokMicrocents: 440000000,
    cachedInputPerMtokMicrocents: 27500000,
    reasoning: { effortValues: ['low', 'medium', 'high'] },
    requestCapabilities: { temperature: false },
    inputModalities: ['text', 'image'],
    outputModalities: ['text'],
    knowledgeCutoff: '2024-05',
    description: 'Fast o-series model for compact reasoning, coding, and tool use',
  },
};

/** The SHA-256 of this catalog's own data — changes when, and only when, what we ship changes. */
export const CATALOG_SHA256 = 'a40975f15ee02a1ecc52383e3636ba9c89fefcf1f0adf7c941107cc5800e1b91';
